<!DOCTYPE HTML>
<html>
    <head>
        <title>Flisol</title>
        <base href="http://<?php echo $_SERVER["HTTP_HOST"]?>/prefered/public/" />
        
        <meta name="viewport" content="user-scalable=no, width=device-width" />
        <meta http-equiv="Content-type" content="text/html;charset=utf-8" />
                
        <link rel="stylesheet" href="style/jquery.mobile-1.0.1.min.css" type="text/css" />
        <link rel="stylesheet" href="style/main.css" type="text/css" />
        <script type="text/javascript" src="js/jquery-1.7.1.min.js"></script>
        <script type="text/javascript" src="js/jquery.mobile-1.0.1.min.js"></script>
    </head>
    <body>
        <div data-role="page" data-theme="b">