<?php require 'header.phtml'; ?>
<div data-role="header" data-posistion="fixed">
    <a class="back" href="#back">Voltar</a>
    <h1>FLISOL</h1>
</div>
<div data-role="content">
    <h2><?php echo $data['nome']?></h2>
    <h3>Por: <?php echo $data['palestrante']?></h3>
    <a class="btn verde" href="<?php echo $data['id']?>/gostou">Curti</a> &nbsp;
    <a class="btn vermelho" href="<?php echo $data['id']?>/nao_gostou">Não Curti</a>
</div>
<?php require 'footer.phtml'; ?>